# Data Settings
phase: valid
pickle_file_path: ./Dataset/cod/R2C7K_pickle.pkl
model_weight: ./ckpt/best_model.pth
snapshot_path: ./ckpt
save_seg_img_path: ./ckpt/predicted_masks

# valid Settings
GPUs: [0]
num_workers: 4
batch_size: 1
seed: 2333

# Model Settings
in_channel: 4
out_channels: 4
num_res_blocks: 2
ch: 32
ch_mult: [1,2,4,4]

# Loss Settings
w_rec: 1
